### ISSUE TITLE
refactor(ddb): DDb models, and connection

### ISSUE THREAD

**Issue by NamelsKing** [Badger-Finance/badger-api#1152]
# Background

Sometime it's hard to find model u need. It can happen that we dont use some of them. And one of the main issues here is to look, mb we can optimize connection to ddb, to save some time in lambdas.

## Tasks

- [ ] Gather all models in one place
- [ ] If model is redundant or unused, rm it
- [ ] Research possibility of ddb connection optimization

**Comment by NamelsKing** [comment]
https://github.com/Badger-Finance/badger-api/pull/1156

**Comment by axejintao** [comment]
we should consider probably moving any kind of historically persisted datas into their own packages, 

- persistence
- ddb-models

or some other naming to help lean this repo some

**Comment by axejintao** [comment]
we could probably remove things such as the indexers from here as well and have them run separately to keep the api truly just an api and allow table management either via other tools or via a separate serverless build. 

wonder if this helps at all in our migration or possible data sharing for entities such as rewards or otherwise
