### ISSUE TITLE
feat: latest vault earn indexer

### ISSUE THREAD

**Issue by btcookies** [Badger-Finance/badger-api#1364]
# Background

Similar to the claimable balances indexer, have a lambda that runs every hour (up for discussion) and pulls latest earns using etherscan api. Similar code is written in python to pull latest harvests from vaults (here)[https://github.com/Badger-Finance/python-keepers/blob/main/src/web3_utils.py#L129] that can be adapted to ethers and used in program.

## Requirements

- [ ] Latest earn timestamps are stored in dynamodb for every production vault in registry
- [ ] Earn indexer lambda running on cron

## Tasks

- [ ] Cron lambda indexing latest vault earns from keeper acl
- [ ] serverless infra set up for new dynamo table and schema
