### ISSUE TITLE
epic: vault history generation tool

### ISSUE THREAD

**Issue by axejintao** [Badger-Finance/badger-api#1532]
# Summary

Through the past two years, the capturing of vault history has undergone several iterations - the most recent capturing information most pertinent to yield captures. Older datas does not have all the yield information (i.e. grossApr) and some of the newer information is bad due to bugs in estimation at the time. 

## Requirements

- create an indexing tool to rebuild a vault history from existing or persisted vault information starting at `createdAt` timestamp 
- yield data should include all active schedules, and all vault yield apr at the time
- vault history updates should be executable on demand with overwriting old data
- vault apr history does not need to include historic trade data as it is not persisted in any meaningful way currently
- snapshots should be done at the lowest chart granularity (hourly) and utilize existing charting frameworks to append data

## Extension

- as part of a migration of AWS accounts this process will be used to recreate vault data on the new account without the need for a mgiration

### Tasks

- [ ] create a runnable job, indexer, or patch for an on demand vault indexer (skeleton - invocable targeting one or many vaults)
- [ ] implement historic yield attributions derived from active schedules
- [ ] implement historic yield attributions derived from persisted yield events
- [ ] implement retroactive current yield (yield estimates) support via archive queries against last harvest

attn: @btcookies
