### ISSUE TITLE
fix(charts): Default values in historic data in case of request failure

### ISSUE THREAD

**Issue by NamelsKing** [Badger-Finance/badger-api#1539]
# Background

Network IO can fail with different causes, this leads default to be saved data in historic snapshots, indexeres etc. One happened with `getStrategyInfo` for charts, thus we have `0x0000` and null values for some rows

## Requirements

- [ ] Default data should be fixed and replaced with relevant onchain variant
- [ ] IO requests shouldnt fail in indexers, or at least do some retries

## Tasks

- [ ] Make patch, that will request onchain data and save it to ddb
- [ ] Some retry wrapper for io functions

**Comment by NamelsKing** [comment]
https://github.com/Badger-Finance/badger-api/pull/1550
