### ISSUE TITLE
feat: Portal governance 

### ISSUE THREAD

**Issue by NamelsKing** [Badger-Finance/badger-api#1585]
# Background

Start after https://github.com/Badger-Finance/badger-sdk/issues/283 is complete to 2nd step.

## Tasks

- [ ] Create indexer for governance items and persist them in ddb
- [ ] Cover indexer with tests
- [ ] New governance controller:
      1. getProposals - provide summary of proposals in a paginated state including info such as
        - proposal id
        - proposal state
        - time proposed
      2. getProposalData - provide break down of proposal information
        - proposer
        - num approved / rejected
        - proposal state
        - time proposed
        - proposal state history
- [ ] Provide tests coverage for controller
